INSERT INTO ROLE VALUES (1, 'ADMIN');
INSERT INTO ROLE VALUES (2, 'STUDENT');
INSERT INTO ROLE VALUES (3, 'TUTOR');

INSERT INTO SUBJECT VALUES (1, 'Math');
INSERT INTO SUBJECT VALUES (2, 'Art');
INSERT INTO SUBJECT VALUES (3, 'Other');